task: detection

num_classes: 8
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/cv_task/ALARAD_Strawberry_Dataset_final/ALARAD_Strawberry_1060_c1/images/train/
    ann_file: /home/cv_task/ALARAD_Strawberry_Dataset_final/ALARAD_Strawberry_1060_c1/annotations/train_STR.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/cv_task/ALARAD_Strawberry_Dataset_final/ALARAD_Strawberry_1060_c1/images/val/
    ann_file: /home/cv_task/ALARAD_Strawberry_Dataset_final/ALARAD_Strawberry_1060_c1/annotations/val_STR.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False